### ISSUE TITLE
PHP CS Fixer stop working

### ISSUE THREAD

**Issue by michaloravec** [adael/SublimePhpCsFixer#40]
Since today php cs fixer stop working, on Sublime Console I got this:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1335, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\micha\AppData\Roaming\Sublime Text 3\Installed Packages\PHP CS Fixer.sublime-package\SublimePhpCsFixer.py", line 322, in is_enabled
  File "C:\Users\micha\AppData\Roaming\Sublime Text 3\Installed Packages\PHP CS Fixer.sublime-package\SublimePhpCsFixer.py", line 349, in is_supported_scope
  File "C:\Users\micha\AppData\Roaming\Sublime Text 3\Installed Packages\PHP CS Fixer.sublime-package\SublimePhpCsFixer.py", line 355, in is_excluded
  File "C:\Users\micha\AppData\Roaming\Sublime Text 3\Installed Packages\PHP CS Fixer.sublime-package\SublimePhpCsFixer.py", line 145, in get
AttributeError: 'NoneType' object has no attribute 'get'
```

I guess it's something with the PR which was merged today.

**Comment by adael** [comment]
Ok, lets rollback these changes. Thanks you!!

**Comment by sander3** [comment]
Yeah, I think package control automatically flagged the package due to the errors to be disabled. Re-installation is not possible for disabled package, since the package will not be listed. Re-enabling the package solves the issue.

Stating this merely for people having the same issue :)
